[tool.poetry]
name = "oeq-cookie-clicker"
version = "0.1.0"
description = ""
authors = ["Millo <23leeuw@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
serial = "^0.0.97"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
